name: Deploy frontend to Dev

on:
  push:
    branches: [development]

jobs:
  deploy:
    # needs: build-and-push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      - name: Build Project
        run: npm run development

      - name: Clean remote front folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET2 }}
          username: alhagni
          password: ${{ secrets.PASS }}
          script: |
            rm -rf ~/public_html/business-smart.alhagni.com/front/*
            mkdir -p ~/public_html/business-smart.alhagni.com/front

      - name: Upload dist to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET2 }}
          username: alhagni
          password: ${{ secrets.PASS }}
          source: "dist/*"
          target: "~/public_html/business-smart.alhagni.com/front/"
          strip_components: 1


  # build-and-push:
  #   name: Build and Push Docker Image
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Log in to Docker Hub
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #     - name: Set Image Tag
  #       id: vars
  #       run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

  #     - name: Build Docker Image with both tags
  #       run: |
  #         docker build -t ahmedhoss22/buisness-smart-front:${{ env.TAG }} .
  #         docker tag ahmedhoss22/buisness-smart-front:${{ env.TAG }} ahmedhoss22/buisness-smart-front:production

  #     - name: Push Docker Images
  #       run: |
  #         docker push ahmedhoss22/buisness-smart-front:${{ env.TAG }}
  #         docker push ahmedhoss22/buisness-smart-front:production

